"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['SmartStitchGUI.py']
DATA_FILES = [('images',["SmartStitchLogo.png", "SmartStitchLogo.ico", "SmartStitchLogo.icns"]), './gui_theme']
OPTIONS = {'iconfile':'SmartStitchLogo.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
